FROM alpine:latest

#RUN apk update
#RUN apk add bash git curl tar
#
## install flutter
#RUN curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.6-stable.tar.xz
#RUN tar xvf flutter_linux_3.19.6-stable.tar.xz --directory=/usr/bin/
#
#RUN export PATH="/usr/bin/flutter/bin:$PATH"
#
#ENTRYPOINT ["flutter", "doctor"]

ENTRYPOINT ["ping", "-c", "1", "google.com"]