name: enigma
description: 'Frontend for Enigma'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_secure_storage: ^9.1.1

  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  test: any

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
