name: enigma
description: 'Frontend for Enigma'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.1
  http: ^1.2.1
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  test: ^1.24.9
  flutter_lints: ^4.0.0

flutter:
  assets:
    - flutter.env
  uses-material-design: true
  fonts:
  - family: Wallau
    fonts:
    - asset: ./fonts/wallau.ttf
