name: enigma
description: 'Frontend for Enigma'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any

  flutter_lints: ^3.0.0

  flutter_driver: 
    sdk: flutter

flutter:
  uses-material-design: true
