name: enigma
description: 'Frontend for Enigma'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_secure_storage: ^9.2.1

  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  test: 1.25.2
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  fonts:
  - family: Wallau
    fonts:
    - asset: ./fonts/wallau.ttf
