stages:
  - prebuild
  - linter
  - test
  - build
  - scanner
  - e2e-test
  - clean

include:
  - local: '/.ci/build.yml'
  - local: '/.ci/scanner.yml'
  - local: '/.ci/test.yml'

clean:
  stage: clean
  image: docker:cli
  script:
    - docker image rm -f $( docker images --quiet ) || true
    - docker image rm -f $( docker images --quiet ) || true
  rules:
    - if: "$NIGHTLY_BUILD"
