stages:
  - prebuild
  - linter
  - test
  - build
  - scanner
  - e2e-test
  - clean

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: always

include:
  - local: '/.ci/build.yml'
  - local: '/.ci/scanner.yml'
  - local: '/.ci/test.yml'

clean:
  stage: clean
  image: docker:cli
  script:
    - docker image rm -f $( docker images --quiet ) || true
    - docker image rm -f $( docker images --quiet ) || true
  rules:
    - if: "$NIGHTLY_BUILD"
