services:
    database:
        image: postgres:16-alpine
        environment:
            LANG: de_DE.utf8
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

        networks:
            enigma-network:
                ipv4_address: ${IP_POSTGRES}

    webserver:
        build: ./backend
        networks:
            enigma-network:
                ipv4_address: ${IP_FASTAPI}

        depends_on:
            database:
                condition: service_started

        env_file:
            - .env

    website:
        build: ./frontend
        ports:
            - 8080:8080
        networks:
            enigma-network:
                ipv4_address: ${IP_FLUTTER}

        depends_on:
            webserver:
                condition: service_started

networks:
    enigma-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1

volumes:
    database-storage:
