version: "3.8"

services:
    database:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin1234!

networks:
    enigma-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1

volumes:
    database-storage:
