include: "/.ci/ci-templates.yml"

build-flutter-builder:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/flutter"
    NAME: "/flutter-builder"
  rules:
    - if: "$NIGHTLY_BUILD"
  needs: []

build-backend-rust:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: "backend/rustlib"
  rules:
    - if: "$NIGHTLY_BUILD"
  needs: []

build-python-tester-linter:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/linter-tester"
    NAME: "/python-tester-linter"
  rules:
    - if: "$NIGHTLY_BUILD"
  needs:
    - job: build-backend-rust
      optional: true

build-scanner:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/scanner"
    NAME: "/scanner"
  rules:
    - if: "$NIGHTLY_BUILD"
  needs: []

build-backend:
  extends: .build-docker
  variables:
    DOCKERPATH: "backend"
  needs:
    - job: build-backend-rust
    - job: unit-integration-test
    - job: lint-backend

build-frontend:
  extends: .build-docker
  variables:
    DOCKERPATH: "frontend"
  needs:
    - job: lint-frontend
    - job: build-flutter-builder
      optional: true
