include: "/.ci/ci-templates.yml"

build-flutter-builder:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/flutter"
    NAME: "/flutter-builder"
  rules:
    - if: "$NIGHTLY_BUILD"

build-python-tester-linter:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/linter-tester"
    NAME: "/python-tester-linter"

build-scanner:
  stage: prebuild
  extends: .build-docker
  variables:
    DOCKERPATH: ".docker-builds/scanner"
    NAME: "/scanner"
  rules:
    - if: "$NIGHTLY_BUILD"

build-backend:
  extends: .build-docker
  variables:
    DOCKERPATH: "backend"

build-frontend:
  extends: .build-docker
  variables:
    DOCKERPATH: "frontend"
